services:
  api_gateway:
    build:
      context: ./src
      dockerfile: ./api_gateway/Dockerfile
      args:
        - API_PORT
    container_name: api_gateway
    working_dir: /usr/src/app
    depends_on:
        db_node_1:
          condition: service_healthy
        account:
          condition: service_healthy
        user:
          condition: service_healthy

    ports:
      - "8000:8000"
    env_file:
      - ".db_env"
      - ".api_env"
      - ".account_env"
      - ".user_env"
    command:
      --port 8000 --host 0.0.0.0
    
  account:
    build:
      context: ./src/services/account
      args:
        - ACCOUNT_SERVICE_PORT
    container_name: account
    working_dir: /usr/src/app
    depends_on:
        db_node_1:
          condition: service_healthy

    ports:
      - "50051:50051"
    env_file:
      - ".db_env"
      - ".api_env"
      - ".account_env"

    healthcheck:
      test: "python ./health_check/health_check.py"
      interval: 15s
      timeout: 1s
      retries: 5
    
  user:
    build: 
      context: ./src/services/user
      args:
        - USER_SERVICE_PORT
    container_name: user
    working_dir: /usr/src/app
    depends_on:
        db_node_1:
          condition: service_healthy

    ports:
      - "50052:50052"
    env_file:
      - ".db_env"
      - ".api_env"
      - ".user_env"

    healthcheck:
      test: "python ./health_check/health_check.py"
      interval: 15s
      timeout: 1s
      retries: 5
  
  db_node_1:
    build: ./src/postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - ".db_env"
      - ".api_env"
    healthcheck:
      test: "psql -h localhost -U postgres -d company"
      interval: 15s
      timeout: 1s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: