services:
  api_gateway:
    build: ./src/api_gateway
    container_name: api_gateway
    working_dir: /usr/src/app
    depends_on:
        db-node-1:
          condition: service_healthy

    ports:
      - "8000:8000"
    env_file:
      - ".db_env"
      - ".api_env"
    command:
      --port 8000 --host 0.0.0.0
    
  db-node-1:
    build: ./src/postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - ".db_env"
      - ".api_env"
    healthcheck:
      test: "psql -h localhost -U postgres -d company"
      interval: 15s
      timeout: 1s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: